### ISSUE TITLE
how to get the html source code of a dynamic website

### ISSUE THREAD

**Issue by zhizunbao84** [fate0/pychrome#13]
`import pychrome

browser = pychrome.Browser(url="http://127.0.0.1:9222")
tab = browser.new_tab()
def request_will_be_sent(**kwargs):
    print("loading: %s" % kwargs.get('request').get('url'))
tab.Network.requestWillBeSent = request_will_be_sent
tab.start()
tab.Network.enable()
tab.Page.enable()
bbb = tab.Page.navigate(url="http://book.jd.com/booktop/0-0-0.html?category=1713-0-0-0-10001-1#comfort", _timeout=5)
frameId = bbb["frameId"]
print(frameId)
aaa = tab.Page.getResourceContent(frameId=frameId, url="http://book.jd.com/booktop/0-0-0.html?category=1713-0-0-0-10001-1#comfort")
print(aaa)
tab.wait(5)
tab.stop()
browser.close_tab(tab)`

with this code, it doesnot get the final html source code.

**Comment by fate0** [comment]
try:

```
tab.Runtime.evaluate(expression="document.documentElement.outerHTML")
```

**Comment by zhizunbao84** [comment]
i look around the document of the Google Chrome Dev Protocol.
there is a function called tab.Network.getResponseBody(RequestId=xxx),but i donot know how to get the RequestId

**Comment by zhizunbao84** [comment]
and also i test your method:`tab.Runtime.evaluate(expression="document.documentElement.outerHTML")`
but i donot get what i want

**Comment by einverne** [comment]
@zhizunbao84 You can get the `RequestId` from the listener callback, but actually you cannot get the real html rendered after js executed from `Network.getResponseBody()` method. You should try fate0's method. It works fine.
