### ISSUE TITLE
how to get whole page loaded event?

### ISSUE THREAD

**Issue by letlet** [fate0/pychrome#14]
I have tried both:
tab.Page.loadEventFired =  loadEventFired
tab.set_listener("Page.loadEventFired", loadEventFired)
None of them works.
I turn DEBUG on and just get:
◀ RECV {"method":"Network.dataReceived","params":{"requestId":"9480.27","timestamp":145931.801829,"dataLength":43,"encodedDataLength":0}}
◀ RECV {"method":"Network.dataReceived","params":{"requestId":"9480.27","timestamp":145931.802118,"dataLength":0,"encodedDataLength":43}}
◀ RECV {"method":"Network.loadingFinished","params":{"requestId":"9480.27","timestamp":145931.800791,"encodedDataLength":299}}

just Network.loadingFinished event, no Page.loadEventFired

**Comment by fate0** [comment]
try `tab.Page.enable()`

**Comment by letlet** [comment]
Already in my code ,same result.
this is part of my code:

self.urls = []

tab = self.browser.new_tab()

def responseReceived(**kwargs):
    url = kwargs.get('response').get('url')
    self.urls.append(url)

tab.Network.responseReceived = responseReceived

def loadEventFired():
	print 'loadEventFired'

tab.Page.loadEventFired = loadEventFired

tab.start()

tab.Network.enable()

tab.Page.navigate(url=self.url, _timeout=8)

tab.wait(8)

tab.stop()

self.browser.close_tab(tab)

**Comment by einverne** [comment]
I am using `Page.domContentEventFired` , if you set a listen to this event, you can get notification when whole page loaded. You can check this link: <https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-domContentEventFired>

**Comment by pxpwoa** [comment]
> I am using `Page.domContentEventFired` , if you set a listen to this event, you can get notification when whole page loaded. You can check this link: https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-domContentEventFired

Can you give a code example of it ?
