### ISSUE TITLE
headerTemplate and footerTemplate doesn't work in printToPDF

### ISSUE THREAD

**Issue by demonno** [fate0/pychrome#17]
python version: tried 2.7, 3.7
pychrome version: 0.2.2 

Using [examples/multi_tabs_pdf.py](https://github.com/fate0/pychrome/blob/master/examples/multi_tabs_pdf.py)

Modified printing part: 

```python

Page.printToPDF(
    displayHeaderFooter=True,
    printBackground=False,
    landscape=False,
    scale=1,
    marginTop=2.0833333333333335,
    marginBottom=2.0833333333333335,
    paperWidth=8.5,
    paperHeight=11,
    marginLeft=0,
    marginRight=0,
    pageRanges="",
    headerTemplate="<h1>Header text</h1>",
    footerTemplate="<h1>Footer text</h1>"
)

```

pychrome debug SEND ►

```json

{
  "method": "Page.printToPDF",
  "params": {
    "displayHeaderFooter": true,
    "printBackground": false,
    "landscape": false,
    "scale": 1,
    "marginTop": 2.0833333333333335,
    "marginBottom": 2.0833333333333335,
    "paperWidth": 8.5,
    "paperHeight": 11,
    "marginLeft": 0,
    "marginRight": 0,
    "pageRanges": "",
    "headerTemplate": "<h1>Header text</h1>",
    "footerTemplate": "<h1>Footer text</h1>"
  },
  "id": 1005
}

```

As a result pdf is rendered but with only default header and footer.

Additional note:
When using [puppeteer](https://github.com/GoogleChrome/puppeteer/blob/master/examples/pdf.js)

On same page with exactly same parameters, it works 
puppeteer debug SEND ► output
```json
{
  "id": 12,
  "method": "Page.printToPDF",
  "params": {
    "landscape": false,
    "displayHeaderFooter": true,
    "headerTemplate": "<h1>Header text</h1>",
    "footerTemplate": "<h1>Footer text</h1>",
    "printBackground": false,
    "scale": 1,
    "paperWidth": 8.5,
    "paperHeight": 11,
    "marginTop": 2.0833333333333335,
    "marginBottom": 2.0833333333333335,
    "marginLeft": 0,
    "marginRight": 0,
    "pageRanges": ""
  }
}
```

**Comment by sonirico** [comment]
Both "headerTemplate" and "footerTemplate" must be a `<div>` element for them to be recognized by Chrome.

**Comment by dodiws** [comment]
@demonno are you sure your pychrome and puppeteer access the same chrome devtool server?

I encounter similar problem, in my case its because my current chrome devtool `printToPDF` method had not supported `headerTemplate` and `footerTemplate` params. You can make sure by opening [localhost:9222/json/protocol](http://localhost:9222/json/protocol) (or whatever your devtool server address) search for `printToPDF` method and see whether those params supported.

Updating chrome should fix that.

**Comment by demonno** [comment]
Currently checking again with:

* Chrome-devtools version `72.0.3626.121`
* `pychrome==0.2.2`

http://localhost:9222/json/protocol -`printToPDF` shows both `headerTemplate` and `footerTemplate` are supported.

And when I run same example again it works :tada: 
Thanks @dodiws
