### ISSUE TITLE
Error in multi_tabs_navigate.py example

### ISSUE THREAD

**Issue by geekscrapy** [fate0/pychrome#18]
`tab.Network.setRequestInterceptionEnabled(enabled=True)`

I get the following error when the above line is hit:

`
/Users/XXX/Work/py3imports/lib/python3.6/site-packages/pychrome/tab.py:174: UserWarning: Network.setRequestInterceptionEnabled error: 'Network.setRequestInterceptionEnabled' wasn't found
  warnings.warn("%s error: %s" % (_method, result['error']['message']))
Traceback (most recent call last):
  File "test.py", line 98, in <module>
    main()
  File "test.py", line 86, in main
    tab.Network.setRequestInterceptionEnabled(enabled=True)
  File "/Users/XXX/Work/py3imports/lib/python3.6/site-packages/pychrome/tab.py", line 175, in call_method
    raise CallMethodException("calling method: %s error: %s" % (_method, result['error']['message']))
pychrome.exceptions.CallMethodException: calling method: Network.setRequestInterceptionEnabled error: 'Network.setRequestInterceptionEnabled' wasn't found
`

**Comment by fate0** [comment]
require chrome version >= 63
