### ISSUE TITLE
Blocking Page.Navigate

### ISSUE THREAD

**Issue by geekscrapy** [fate0/pychrome#22]
Page.Navigate appears to be blocking. How would you utilise Network.requestIntercepted and related Network.continueInterceptedRequest in this case? All other events appear to be queued, which is not real-time.

Would it be best to attempt to multithread the navigate command?

**Comment by geekscrapy** [comment]
This could be solved by defining the callbacks proir to the navigate call like this:

https://groups.google.com/a/chromium.org/forum/m/#!topic/headless-dev/uvms04dXTIM

**Comment by geekscrapy** [comment]
Is there a way you know of to set a timeout on the Page.Navigate call?

**Comment by fate0** [comment]
@geekscrapy  `tab.Page.navigate(url="https://github.com/fate0/pychrome", _timeout=5)`

**Comment by geekscrapy** [comment]
Thanks, apologies, completely forgot to recheck the demos.

Doesn't the Navigate call continue in the background though? As there isn't an additional call to chrome to cancel the request? Is this correct?

**Comment by fate0** [comment]
@geekscrapy use `tab.Page.stopLoading()` to cancel the request
