### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9222): Max retries exceeded with url: /json/new 

### ISSUE THREAD

**Issue by karankrish** [fate0/pychrome#31]
![image](https://user-images.githubusercontent.com/22211883/45623524-45e7f600-baa5-11e8-81ca-cbfd66bb03c0.png)

**Comment by fy975713384** [comment]
Maybe you need to close all other chrome processes first.

**Comment by fate0** [comment]
network problem or Chrome is not configured correctly
