### ISSUE TITLE
tab.Page.addScriptToEvaluateOnNewDocument not working?

### ISSUE THREAD

**Issue by nleftheris** [fate0/pychrome#37]
I can not get this method to work at all. It shows in the debug log and I am given an id and identifier response, but the scripts never seem to be executed when I load pages. I'm not really sure how this issue is specific to PyChrome, but the same method is working on the same Chromium setup with Selenium, so I think it must be.

To reproduce, just try adding something like this to the demo program and you'll be able to see that the console receives no alerts:

`tab.Page.addScriptToEvaluateOnNewDocument(source='console.log("test")')`

**Comment by nleftheris** [comment]
I realized shortly after posting that this was happening because I had not called tab.Page.enable(). Issue closed.

**Comment by mattwark** [comment]
Wow this just saved me a lot of time.
