### ISSUE TITLE
How to tracing?

### ISSUE THREAD

**Issue by kiryakm** [fate0/pychrome#50]
I'm trying to trace my JS code but i can't get my performance mark in trace log.
My JS code:
```HTML
<script>
  performance.mark('my-start');

  for (let i = 0; i < 5; i++) {
    for (let j = 0; j < 2; j++) {
      a = Math.cbrt(Math.random() * 100);
      console.log(a);
    }         
  }
  performance.mark('my-end');
  performance.measure('my-benchmark', 'my-start', 'my-end');
</script>
```
Python code:
```Python
import pychrome
import json

browser = pychrome.Browser(url="http://127.0.0.1:9222")

tab = browser.new_tab()
open('trace_log.json', 'w').close()

def tracing_complete(**kwargs):
    eof = False
    while not eof:
        data = tab.call_method("IO.read", handle=kwargs["stream"])
        eof = data["eof"]
        if data["data"]:
            data = json.loads(str(data["data"]))
            with open('data.json', 'a') as f:
                json.dump(data, f, indent=4)

    tab.call_method("IO.close", handle=kwargs["stream"])

tab.set_listener("Tracing.tracingComplete", tracing_complete)

tab.start()
tab.call_method("Network.enable")

tab.call_method("Tracing.start", transferMode='ReturnAsStream', _timeout=5)
tab.call_method("Page.navigate", url="my_page.html", _timeout=5)
tab.call_method("Tracing.end",  _timeout=5)

tab.wait(5)
tab.stop()
browser.close_tab(tab)
```

It seems what i'm dooing something wrong since i can get my mark using chrome performance profiling.

**Comment by yuhuan0311** [comment]
> I'm trying to trace my JS code but i can't get my performance mark in trace log.
> My JS code:
> 
> ```
> <script>
>   performance.mark('my-start');
> 
>   for (let i = 0; i < 5; i++) {
>     for (let j = 0; j < 2; j++) {
>       a = Math.cbrt(Math.random() * 100);
>       console.log(a);
>     }         
>   }
>   performance.mark('my-end');
>   performance.measure('my-benchmark', 'my-start', 'my-end');
> </script>
> ```
> 
> Python code:
> 
> ```python
> import pychrome
> import json
> 
> browser = pychrome.Browser(url="http://127.0.0.1:9222")
> 
> tab = browser.new_tab()
> open('trace_log.json', 'w').close()
> 
> def tracing_complete(**kwargs):
>     eof = False
>     while not eof:
>         data = tab.call_method("IO.read", handle=kwargs["stream"])
>         eof = data["eof"]
>         if data["data"]:
>             data = json.loads(str(data["data"]))
>             with open('data.json', 'a') as f:
>                 json.dump(data, f, indent=4)
> 
>     tab.call_method("IO.close", handle=kwargs["stream"])
> 
> tab.set_listener("Tracing.tracingComplete", tracing_complete)
> 
> tab.start()
> tab.call_method("Network.enable")
> 
> tab.call_method("Tracing.start", transferMode='ReturnAsStream', _timeout=5)
> tab.call_method("Page.navigate", url="my_page.html", _timeout=5)
> tab.call_method("Tracing.end",  _timeout=5)
> 
> tab.wait(5)
> tab.stop()
> browser.close_tab(tab)
> ```
> 
> It seems what i'm dooing something wrong since i can get my mark using chrome performance profiling.

hello,can u run successfully with the python code?

**Comment by kiryakm** [comment]
Yes, i figure it out. You have to wait until page load and then call Tracing.end. In code you have to do something like this:
```python
import threading
import pychrome

page_loaded_event = threading.Event()

tab.set_listener("Network.requestWillBeSent", request_will_be_sent)
tab.set_listener("Tracing.tracingComplete", tracing_complete)
tab.set_listener("Network.loadingFinished", loading_finished)

def loading_finished(**kwargs):
        self.page_loaded_event.set()
    
def request_will_be_sent(**kwargs):
        tab.wait(1)

def stop_tracing():
        page_loaded_event.wait()
        tab.call_method("Tracing.end")  

my_thread = threading.Thread(target=stop_tracing)
my_thread.start()
tab.start()
tab.call_method("Network.enable")
tab.call_method("Tracing.start", transferMode='ReturnAsStream')
tab.call_method("Page.navigate", url=page_address)
# Waiting for the page to finish loading
tab.wait(5)
my_thread.join()
page_loaded_event.clear()
tab.stop()
```

Hope you get the idea. I'm closing this issue.
